use std::collections::BTreeMap;

use crate::MBox;

impl MBox {
    pub fn derivative(&self, target: &MBox) -> MBox {
        fn reduce_number(m_box: &MBox) -> Option<(u64, MBox)> {
            if !m_box.depth() == 1 {
                return None;
            }
            let is_anti = m_box.is_anti_box();
            let reduced = m_box
                .boxes_ref()
                .iter()
                .map(|(z_box, mul)| {
                    let z_box = z_box.clone().annihilate();
                    let is_anti = z_box.is_anti_box();
                    (
                        z_box,
                        if is_anti {
                            mul.saturating_add(1)
                        } else {
                            mul.saturating_sub(1)
                        },
                    )
                })
                .collect::<BTreeMap<_, _>>();

            if let Some((_, &value)) = reduced.first_key_value() {
                if is_anti {
                    Some((value.saturating_sub(1), MBox::AntiBox(reduced)))
                } else {
                    Some((value.saturating_add(1), MBox::Box(reduced)))
                }
            } else {
                None
            }
        }

        // Base Case
        if self.depth() == 2 {
            let filtered = self
                .boxes_ref()
                .iter()
                .filter_map(|(m_box, mul)| {
                    if let Some((exp, reduced)) = reduce_number(m_box) {
                        Some((reduced, mul * exp))
                    } else {
                        None
                    }
                })
                .collect();

            return if self.is_anti_box() {
                MBox::AntiBox(filtered)
            } else {
                MBox::Box(filtered)
            };
        }

        // This map will collect all the summands generated by the Product Rule
        let mut sum_map = BTreeMap::new();

        // Iterate over every unique factor (key) in the current product
        let map = self.boxes_ref();
        println!("self: {self:#}");
        println!("target: {target}");
        for (factor, &count) in map.iter() {
            if count == 0 {
                continue;
            }

            // --- STEP 1: Differentiate the factor recursively (Chain/Product rule) ---
            let inner_derivative = factor.derivative(target);
            println!("fact: {factor}");
            println!("{inner_derivative}");

            // If the derivative isn't zero (an empty map), we process the terms
            if !MBox::is_zero(&inner_derivative) {
                // --- STEP 2: Reduce the count of the current factor by 1 ---
                let mut reduced_product_map = map.clone();
                if count == 1 {
                    reduced_product_map.remove(factor);
                } else {
                    reduced_product_map.insert(factor.clone(), count - 1);
                }

                // --- STEP 3: Multiply and add the terms to our sum_map ---
                // Extract the inner terms from the derivative sum
                let inner_terms = inner_derivative.into_boxes();
                for (term, term_count) in inner_terms {
                    // For each term in the derivative, combine its components
                    // with our remaining reduced product components
                    let mut combined_term_map = reduced_product_map.clone();
                    let t_map = term.into_boxes();
                    for (k, v) in t_map {
                        *combined_term_map.entry(k).or_insert(0) += v;
                    }

                    // Reconstruct the structural summand
                    let summand = match self {
                        MBox::Box(_) => MBox::Box(combined_term_map),
                        MBox::AntiBox(_) => MBox::AntiBox(combined_term_map),
                    };

                    // Account for both the internal term frequency AND the Power Rule coefficient:
                    // d/dx(x^n) = n * x^(n-1). We multiply the counts together.
                    *sum_map.entry(summand).or_insert(0) += term_count * count;
                }
            }
        }

        match self {
            MBox::Box(_) => MBox::Box(sum_map),
            MBox::AntiBox(_) => MBox::AntiBox(sum_map),
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::num;

    #[test]
    fn test_der_1() {
        let x = var!();
        let prod = var!() * var!() * var!() + var!();

        let der = prod.derivative(&x).annihilate();
        let exp = num!(3) * var!() * var!() + num!(1);

        assert_eq!(der, exp);
    }
}
